## Numpy

In [2]:
import numpy as np

In [3]:
np1=np.array([1,2,3,4])

In [4]:
np1

array([1, 2, 3, 4])

In [5]:
type(np1)

numpy.ndarray

In [7]:
Mat1=np.array([[1,2],[3,4]])

In [8]:
Mat1

array([[1, 2],
       [3, 4]])

In [9]:
type(Mat1)

numpy.ndarray

In [11]:
np1.shape

(4,)

In [12]:
Mat1.shape

(2, 2)

In [13]:
Mat1.dtype

dtype('int32')

In [14]:
Mat1[0,0]=5

In [15]:
Mat1

array([[5, 2],
       [3, 4]])

In [16]:
Mat2=np.arange(0,10,1)

In [17]:
Mat2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
mat3=np.linspace(0,10,20)

In [19]:
mat3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [20]:
mat3.shape

(20,)

In [21]:
Mat4=np.random.rand(5,7)

In [22]:
Mat4

array([[0.47521802, 0.18142582, 0.45855527, 0.22496394, 0.19543789,
        0.13178624, 0.29464069],
       [0.51202655, 0.25196327, 0.63622587, 0.1810424 , 0.84378474,
        0.73574926, 0.90997664],
       [0.78452609, 0.78942334, 0.15788244, 0.87393241, 0.01252575,
        0.21290339, 0.62350503],
       [0.649483  , 0.00666163, 0.34065169, 0.97097466, 0.46515319,
        0.95136049, 0.1639832 ],
       [0.71179452, 0.69194246, 0.58074738, 0.84422667, 0.2725688 ,
        0.82774419, 0.42154368]])

In [23]:
Mat4.shape

(5, 7)

In [24]:
Mat4.dtype

dtype('float64')

In [29]:
Mat5=np.random.randn(6,9)

In [30]:
Mat5

array([[-1.52810229e+00, -7.80509353e-01, -9.77895112e-01,
         3.54217777e-01,  1.58033645e+00,  7.43036527e-01,
         2.72380351e-01,  3.30153005e-01,  5.36928364e-02],
       [ 9.06741492e-01, -1.24584949e+00, -1.00087155e+00,
        -1.13688389e+00, -1.60171546e-01, -4.92234079e-01,
         1.00563249e+00,  2.23507964e+00, -7.55313212e-01],
       [-8.72042366e-03,  5.97643130e-01,  5.36258295e-01,
        -5.04463445e-01,  2.02658044e+00,  1.38356725e+00,
         5.95449183e-01,  1.55419408e+00, -1.78723999e+00],
       [-8.71773998e-01,  6.95880690e-01,  1.41476363e+00,
        -8.74194164e-01, -8.10177559e-02,  8.22752618e-01,
         5.05405888e-01, -2.55921783e-01,  3.39368247e-01],
       [-1.01383935e-01, -4.31354869e+00, -1.18691066e+00,
         9.10148384e-01,  8.51380944e-01, -1.02042368e-01,
        -1.13873485e-01,  1.15631247e+00,  4.73905788e-01],
       [ 7.95913755e-01, -1.15714061e+00, -4.78319478e-01,
        -7.09600486e-01, -5.26214902e-01, -9.214796

In [31]:
Mat5[0,0]

-1.5281022876082024

In [32]:
Mat5[0:3,:]

array([[-1.52810229, -0.78050935, -0.97789511,  0.35421778,  1.58033645,
         0.74303653,  0.27238035,  0.330153  ,  0.05369284],
       [ 0.90674149, -1.24584949, -1.00087155, -1.13688389, -0.16017155,
        -0.49223408,  1.00563249,  2.23507964, -0.75531321],
       [-0.00872042,  0.59764313,  0.53625829, -0.50446344,  2.02658044,
         1.38356725,  0.59544918,  1.55419408, -1.78723999]])